In [1]:
import Lineales as li
import numpy as np


A = np.array([[2.0 , -1.0, 0.0],
     [1.0, 6.0, -2.0],
     [4.0, -3.0,8.0]])
b = np.array([2.0, -4.0, 6.0])
x0 = np.array([0.0,0.0,0.0])

solucion, error = li.gauss_Seidel(A, b, x0)
print(f"Solucion: {solucion}")
print(f"Error: {error}")

Converge en 7 iteraciones
Solucion: [ 0.63975677 -0.71999311  0.1601242 ]
Error: 0.0004933526868082794


# b) Investigar como leer un txt con una matriz 
la matriz que yo elegi es de 10x10

In [4]:
#b
    # Primera opcion
"""A = []
with open('matriz.txt', 'r') as archivo:
    for linea in archivo:
        fila = [float(valor) for valor in linea.strip(',')]
        A.append(fila)"""

A = np.loadtxt('A.txt', delimiter=',')
b = np.loadtxt('b.txt', delimiter=',')
x0 = np.loadtxt('X.txt', delimiter=',')

print(type(A))
print(A)
solucion_txt, error_txt = li.gauss_Seidel(A,b,x0)
print(f"Solucion: {solucion_txt}")
print(f"Error: {error_txt}")

<class 'numpy.ndarray'>
[[ -4.  -2.   5.  -2.   5.  -5.  -2.   1.  -5.   3.]
 [  1.  -8.  -4.  -1.   3.  -5.  -4.   2.   2.   2.]
 [ -4.   0.  24.   1.   4.   5.   1.   3.   5.  -3.]
 [ -2.  -2.  -3. -10.   2.  -4.   4.   0.  -1.   1.]
 [ -3.  -3.  -2.   5. -10.  -5.  -4.   0.   3.   4.]
 [  3.   3.   0.  -5.  -3. -24.  -3.  -5.  -4.   2.]
 [ -2.   1.  -1.   2.  -1.  -2. -16.  -3.  -5.   3.]
 [ -5.   5.   2.  -5.  -5.  -3.   4. -18.  -1.  -1.]
 [  2.  -3.  -3.   1.   5.  -1.  -4.   1.  -4.   0.]
 [  2.   2.  -4.  -2.   0.  -1.  -4.  -5.  -4. -32.]]
Converge en 17 iteraciones
Solucion: [-0.94948923  0.22596555 -0.27656651  0.61247982  0.49823969 -0.67046486
  0.25894264  0.0642618   0.7638647  -0.1033692 ]
Error: 0.0009003835779268776


# c) ¿Cómo modificaría el código para implementar el método de Jacobi?

    Lo modificaria en la siguiente linea
    suma += A[i][j]*x[j]
    por lo siguiente
    suma += A[i][j]*x_ant[j]

In [1]:
import Lineales as li
import numpy as np

A = np.loadtxt('A.txt', delimiter=',')
b = np.loadtxt('b.txt', delimiter=',')
x0 = np.loadtxt('X.txt', delimiter=',')

solucion_txt, error_txt = li.Jacobi(A,b,x0)
print(f"solucion: {solucion_txt}")
print(f"Error: {error_txt}")

Converge en 100 iteraciones
solucion: [-0.98947156  0.2237701  -0.27845501  0.6037298   0.50544226 -0.66900321
  0.25460367  0.06822662  0.74199137 -0.10417354]
Error: 0.04792926156014499


# 4)  Método SOR

In [24]:
import Lineales as li
import numpy as np

A = [[4.0,3.0,0.0],
     [3.0,4.0,-1.0],
     [0.0,-1.0,4.0]]
b = [24.0,30.0,24.0]
x0 = [0.0,0.0,0.0]

valores_prueba= [0.5,0.8,1.0,1.2,1.5,1.8]
for w in valores_prueba:
    print(f" Omega= {w}")
    solucion = li.SOR(A,b,x0,w)

 Omega= 0.5
Iteracion 15: [5.99981689453125, 3.0009384155273438, 6.750652313232422]
 Omega= 0.8
Iteracion 7: [5.9999232000000005, 3.0002841599999996, 6.750117888]
 Omega= 1.0
Iteracion 2: [6.0, 3.0, 6.75]
 Omega= 1.2
Iteracion 8: [5.999984639999999, 3.0001029120000013, 6.7501135872]
 Omega= 1.5
Iteracion 21: [6.000002861022949, 2.9999338388442993, 6.749735668301582]
 Omega= 1.8
Iteracion 77: [6.00000020705239, 2.999978580430213, 6.749626089782106]


In [15]:
import numpy as np
A = np.array([[4.0,3.0,0.0],
     [3.0,4.0,-1.0],
     [0.0,-1.0,4.0]])
valor_propio, vector_propio = np.linalg.eig(A) # retorna los valores propios de la matriz A
print("Valores propios: ",valor_propio)
print("Vectores propios: ",vector_propio)

Valores propios:  [0.83772234 7.16227766 4.        ]
Vectores propios:  [[ 6.70820393e-01  6.70820393e-01  3.16227766e-01]
 [-7.07106781e-01  7.07106781e-01  1.11226195e-16]
 [-2.23606798e-01 -2.23606798e-01  9.48683298e-01]]


In [8]:
import numpy as np

# Definir una matriz cuadrada
A = np.array([[2, 1],
              [1, 2]])

# Calcular valores propios y vectores propios
valores_propios, vectores_propios = np.linalg.eig(A)

print("Valores propios:", valores_propios)
print("Vectores propios:\n", vectores_propios)
n = len(valores_propios)
determinante = 1
for i in range(n):
    determinante *= valores_propios[i]
print(determinante)

Valores propios: [3. 1.]
Vectores propios:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
3.0


In [30]:
import Lineales as li
import numpy as np

A = [[2,-1,-1],
     [0,2,1],
     [-1,1,0.5]]

b = [0,3,0.5]

def Eliminacion_Gauss(A,
                      b,
                      ):
    """
    A: Matriz
    B: Vector
    """
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)
    n = len(b)
    M = np.concatenate((A,b.reshape(n,1)), axis=1) # matriz ampliada (A|b)
    print(M)
    print("")
    for k in range(n-1):
        if M[k,k] == 0:
            raise ValueError(f"Pivote nulo en la fila: {k}. el metodo falla")
        for i in range(k+1, n):
            factor = M[i,k] / M[k,k]
            for j in range(k,n+1):
                M[i,j] -= factor*M[k,j]     # Construyendo matriz U
            M[i,k] = factor #    construyendo matriz L
    print(M)

    x = np.zeros(n)
    for i in range(n-1,-1,-1):
        suma_conocida = np.dot(M[i,i+1:n], x[i+1:n])
        x[i] = (M[i,n] - suma_conocida) / M[i,i]
    return x

x = Eliminacion_Gauss(A,b)
print(f"vector: {x}")

[[ 2.  -1.  -1.   0. ]
 [ 0.   2.   1.   3. ]
 [-1.   1.   0.5  0.5]]

[[ 2.   -1.   -1.    0.  ]
 [ 0.    2.    1.    3.  ]
 [-0.5   0.25 -0.25 -0.25]]
vector: [1. 1. 1.]
